### ISSUE TITLE
RNA004 demultiplex issue

### ISSUE THREAD

**Issue by buhanfeng** [novoalab/SeqTagger#3]
Hi,

Thanks for offering such an excellent tools.

I wonder why SeqTagger doesn't support 96 barcodes schema for RNA004 while RNA004 has became more and more prevalent? Is there any plan for SeqTagger to update such function in the future?

**Comment by enovoa** [comment]
Thank you for your interest. Yes, we have been working in this direction, and we plan to release a 96bc model, hopefully soon. Best, Eva
